Repository openfisca/openfisca-doc, pull requests merged in 2018-04, with the labels that each got.

#125 Fix logo
  README.md
Labels: kind:bug

#122 Clarifies reforms vocabulary
  coding-the-legislation/reforms.md
Labels: flow:support:doing, kind:documentation

#108 Fix typo
  variables.md
Labels: flow:contrib:backlog

#126 Add link to tutorial FAQ
  recipes.md
Labels: flow:team:doing, kind:documentation

#131 Bump API version to v21 in Web API doc
  openfisca-web-api/README.md
Labels: flow:support:doing, kind:documentation

#128 Use OpenFisca on repl.it
  SUMMARY.md
  howto-web-no-local-install.md
  img/replit-homepage.png
  img/replit-run-button.png
  img/replit-upload-drop-button.png
  recipes.md
Labels: flow:team:doing, kind:documentation

#130 Change links to legislation explorer
  coding-the-legislation/legislation_parameters.md
  contribute/README.md
  input_data.md
  openfisca-web-api/README.md
  openfisca-web-api/endpoints.md
  person,_entities,_role.md
Labels: flow:support:doing, kind:documentation

#135 Update contact and community projects list
  community.md
Labels: flow:contrib:doing, kind:documentation
