Repository openfisca/openfisca-doc, pull requests merged in 2019-12, with the labels that each got.

#217 Add test to commit only when staged changes
  publish.sh
Labels: kind:bug

#215 Rename doc openfisca-run-test to openfisca_test
  source/coding-the-legislation/writing_yaml_tests.md
  source/openfisca-python-api/index.md
  source/openfisca-python-api/openfisca_test.rst
  source/openfisca-python-api/test_runner.rst
Labels: kind:documentation

#219 Small formatting / spelling fixes to howto_docker.md
  source/installation/howto_docker.md
Labels: kind:bug, level:starter

#221 Fix broken links
  source/index.md
Labels: kind:bug, level:starter

#220 Skip CI when publishing doc
  publish.sh
Labels: kind:devops, level:starter
